services:
  - type: web
    name: symfony-app
    env: php
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader
    startCommand: php -S 0.0.0.0:10000 -t public
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: change_me_secret
